### ISSUE TITLE
Box2D support

### ISSUE THREAD

**Issue by thomz12** [theolivenbaum/h5#40]
In my project I'd like to use Box2D. Is it possible to port that over from Retyped.box2d? 

Is that something I can look into? Are you decompiling the Retyped packages for that?

**Comment by theolivenbaum** [comment]
Hi @thomz12,

Yeah that's the approach I used before, just decompile with any tool and
replace Retyped with H5.core

I've two packages in my todo list for a while, let's see if I manage to do
the three over this weekend.

Cheers,

Rafael

**Comment by thomz12** [comment]
Thanks for the info! I had I look just now and was able to decompile and get it to compile with my project.
Had a quick test that still didn't quite work, but I'll figure that out tomorrow. :)

**Comment by theolivenbaum** [comment]
Perfect! If you wanna submit the code as a PR I can publish it as a Nuget
package as well

**Comment by thomz12** [comment]
So unfortunatly the original package used for Retpyed.box2d is used just for node applications. (I failed to notice that before)
I can convert it so it can be loaded in a browser, but I can't get the retyped package to work with that. (in the browser)

Do you have any ideas?

**Comment by theolivenbaum** [comment]
To be honest my personal experience with Retyped isn't very good - for all the libraries we use, we just ended up writing our own wrapper classes - much easy to get a consistency experience than the autogenerated one from the typescript definition files used by Retyped. I'm not familiar with Box2D, but if their API is not too crazy might be worth giving it a try.

It's usually as simple as writing a C# method and  directly call the javascript code with something like this:


```csharp
public class MyLib
{ 
    public int DoSomething(string par1, int par2)
    {
        return Script.Write<int>("myLib.doSomething({0}, {1}", par1, par2);
    }
}
```

The trick is that the compiler will emit directly the parameter variables in the final javascript, so that becomes:

```js
return myLib.doSomething(par1, par2);
```

If you need more complex data types, you can create lightweight classes using the [ObjectLiteral] attribute. These classes are compiled to plain javascript objects without any of the C# extra code.

**Comment by theolivenbaum** [comment]
Obviously, use static methods if it's a static library, or create an instance of the library and store it locally in the wrapper class if needed

**Comment by thomz12** [comment]
Thanks again for the tips!
I ended up using p2.js instead, and decompiled the retyped package for that. That seems to work now! 

Would you like to make a nuget package for it? (p2) If you do, I'll open a PR tomorrow.

**Comment by theolivenbaum** [comment]
If you can that would be great!

**Comment by thomz12** [comment]
Cool! I wanted to push a new branch, but it it looks like I'm not allowed to. 

```
remote: Permission to theolivenbaum/h5.git denied to thomz12.
```

**Comment by theolivenbaum** [comment]
I think you've to fork first, push to your fork and then open a PR

**Comment by thomz12** [comment]
Oh duh!
I've opened a PR now.

**Comment by theolivenbaum** [comment]
did that mistake in the past too  😄

Just merged the code, thanks for contributing!

For future reference, I'm leaving these two regexs that I used for cleaning the decompiled code:

- Replace  `\s+{[\n\r]\s+get[\n\r]\s+{(.|[\s\n\r])*?}[\n\r]\s+set[\n\r]\s+{(.|[\s\n\r])*?}\s+}
` with ` { get; set; }`
- Replace `\s+private .*?__BackingField;\r\n` with ` `

The final package should be published on [nuget ](https://www.nuget.org/packages/h5.p2/) soon!
